version: '2'
services:
  runner:
   image: api_runner
   links:
    - server:oasis_api_server
  server:
   image: oasis_api_server
   ports:
     - "8001:80"
   links:
     - mysql:mysql
     - rabbit:rabbit
   environment:
     - RABBIT_PORT=5672
     - MYSQL_PORT=3306
   volumes:
#     - ./log:/var/log/oasis:rw
     - ./upload:/var/www/oasis/upload:rw
     - ./download:/var/www/oasis/download:rw
  worker:
    image: model_execution_worker
    links:
     - mysql:mysql
     - mysql:oasis_mysql
     - rabbit:myrabbit
     - rabbit:oasis_rabbit
    environment:
     - MODEL_SUPPLIER_ID=OasisIM
     - MODEL_VERSION_ID=1
     - RABBIT_PORT=5672
     - MYSQL_PORT=3306
    volumes:
#     - ./log:/var/log/oasis:rw
     - ./upload:/var/oasis/upload:rw
     - ./download:/var/oasis/download:rw
     - ./data/static:/var/oasis/model_data/OasisIM/1:rw
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=celery
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=celery 
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  flower:
    image: iserko/docker-celery-flower 
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672
    entrypoint:
      - flower 
      - --port=5555 
      - --broker_api=http://guest:guest@rabbit:15672/api/"
    links:
     - mysql
     - rabbit:rabbit
